//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blog_challenge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Blog
    {
        public int Bid { get; set; }
        [Required]
        [Display(Name ="Titulo")]
        public string Bttitle { get; set; }
        [Required]
        [Display(Name = "Contenido")]
        public string Bcontent { get; set; }
        [Required]
        [Display(Name = "Categoria")]
        public string BCategory { get; set; }
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> BDate { get; set; }
        public byte[] Bimage { get; set; }
    }
}
