//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blog_challengeCsharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Bid { get; set; }
        public string Bttitle { get; set; }
        public string Bcontent { get; set; }
        public string BCategory { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
    }
}
